# LANGUAGE message translation file for plpython
# Copyright (C) 2009-2022 PostgreSQL Global Development Group
# This file is distributed under the same license as the plpython (PostgreSQL) package.
#
# Use these quotes: « %s »
#
# Guillaume Lelarge <guillaume@lelarge.info>, 2009-2022.
#
msgid ""
msgstr ""
<<<<<<< HEAD
"Project-Id-Version: PostgreSQL 9.6\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2018-09-22 00:08+0000\n"
"PO-Revision-Date: 2018-09-23 15:30+0200\n"
=======
"Project-Id-Version: PostgreSQL 15\n"
"Report-Msgid-Bugs-To: pgsql-bugs@lists.postgresql.org\n"
"POT-Creation-Date: 2023-07-30 09:08+0000\n"
"PO-Revision-Date: 2022-04-12 17:29+0200\n"
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
"Last-Translator: Guillaume Lelarge <guillaume@lelarge.info>\n"
"Language-Team: French <guillaume@lelarge.info>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
<<<<<<< HEAD
"X-Generator: Poedit 2.1.1\n"

#: plpy_cursorobject.c:101
=======
"X-Generator: Poedit 3.0.1\n"

#: plpy_cursorobject.c:72
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "plpy.cursor expected a query or a plan"
msgstr "plpy.cursor attendait une requête ou un plan"

<<<<<<< HEAD
#: plpy_cursorobject.c:184
=======
#: plpy_cursorobject.c:155
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "plpy.cursor takes a sequence as its second argument"
msgstr "plpy.cursor prends une séquence dans son second argument"

<<<<<<< HEAD
#: plpy_cursorobject.c:200 plpy_spi.c:211
=======
#: plpy_cursorobject.c:171 plpy_spi.c:205
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not execute plan"
msgstr "n'a pas pu exécuter le plan"

<<<<<<< HEAD
#: plpy_cursorobject.c:203 plpy_spi.c:214
=======
#: plpy_cursorobject.c:174 plpy_spi.c:208
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Séquence attendue de %d argument, %d obtenu : %s"
msgstr[1] "Séquence attendue de %d arguments, %d obtenus : %s"

<<<<<<< HEAD
#: plpy_cursorobject.c:352
=======
#: plpy_cursorobject.c:321
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "iterating a closed cursor"
msgstr "itération d'un curseur fermé"

<<<<<<< HEAD
#: plpy_cursorobject.c:360 plpy_cursorobject.c:426
=======
#: plpy_cursorobject.c:329 plpy_cursorobject.c:395
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "iterating a cursor in an aborted subtransaction"
msgstr "itération d'un curseur dans une sous-transaction annulée"

<<<<<<< HEAD
#: plpy_cursorobject.c:418
=======
#: plpy_cursorobject.c:387
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "fetch from a closed cursor"
msgstr "récupérer à partir d'un curseur fermé"

<<<<<<< HEAD
#: plpy_cursorobject.c:461 plpy_spi.c:409
=======
#: plpy_cursorobject.c:430 plpy_spi.c:401
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "query result has too many rows to fit in a Python list"
msgstr "le résultat de la requête contient trop de lignes pour être intégré dans une liste Python"

<<<<<<< HEAD
#: plpy_cursorobject.c:512
=======
#: plpy_cursorobject.c:482
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "closing a cursor in an aborted subtransaction"
msgstr "fermeture d'un curseur dans une sous-transaction annulée"

<<<<<<< HEAD
#: plpy_elog.c:127 plpy_elog.c:128 plpy_plpymodule.c:559
=======
#: plpy_elog.c:125 plpy_elog.c:126 plpy_plpymodule.c:530
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "%s"
msgstr "%s"

<<<<<<< HEAD
#: plpy_exec.c:142
=======
#: plpy_exec.c:139
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "unsupported set function return mode"
msgstr "mode de retour non supporté pour la fonction SET"

<<<<<<< HEAD
#: plpy_exec.c:143
=======
#: plpy_exec.c:140
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python set-returning functions only support returning one value per call."
msgstr ""
"les fonctions PL/python renvoyant des ensembles supportent seulement une\n"
"valeur renvoyée par appel."

<<<<<<< HEAD
#: plpy_exec.c:156
=======
#: plpy_exec.c:153
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "returned object cannot be iterated"
msgstr "l'objet renvoyé ne supporte pas les itérations"

<<<<<<< HEAD
#: plpy_exec.c:157
=======
#: plpy_exec.c:154
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""
"les fonctions PL/python renvoyant des ensembles doivent renvoyer un objet\n"
"itérable"

<<<<<<< HEAD
#: plpy_exec.c:171
=======
#: plpy_exec.c:168
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "error fetching next item from iterator"
msgstr "erreur lors de la récupération du prochain élément de l'itérateur"

<<<<<<< HEAD
#: plpy_exec.c:214
=======
#: plpy_exec.c:211
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python procedure did not return None"
msgstr "la procédure PL/python n'a pas renvoyé None"

<<<<<<< HEAD
#: plpy_exec.c:218
=======
#: plpy_exec.c:215
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "la fonction PL/python avec un code de retour « void » ne renvoyait pas None"

<<<<<<< HEAD
#: plpy_exec.c:374 plpy_exec.c:400
=======
#: plpy_exec.c:369 plpy_exec.c:393
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "valeur de retour inattendue de la procédure trigger"

<<<<<<< HEAD
#: plpy_exec.c:375
=======
#: plpy_exec.c:370
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "Expected None or a string."
msgstr "Attendait None ou une chaîne de caractères."

<<<<<<< HEAD
#: plpy_exec.c:390
=======
#: plpy_exec.c:383
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"la fonction trigger PL/python a renvoyé « MODIFY » dans un trigger DELETE\n"
"-- ignoré"

<<<<<<< HEAD
#: plpy_exec.c:401
=======
#: plpy_exec.c:394
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Attendait None, « OK », « SKIP » ou « MODIFY »."

<<<<<<< HEAD
#: plpy_exec.c:451
=======
#: plpy_exec.c:444
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "échec de PyList_SetItem() lors de l'initialisation des arguments"

<<<<<<< HEAD
#: plpy_exec.c:455
=======
#: plpy_exec.c:448
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "échec de PyDict_SetItemString() lors de l'initialisation des arguments"

<<<<<<< HEAD
#: plpy_exec.c:467
=======
#: plpy_exec.c:460
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "function returning record called in context that cannot accept type record"
msgstr ""
"fonction renvoyant le type record appelée dans un contexte qui ne peut pas\n"
"accepter le type record"

<<<<<<< HEAD
#: plpy_exec.c:684
=======
#: plpy_exec.c:677
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "while creating return value"
msgstr "lors de la création de la valeur de retour"

<<<<<<< HEAD
#: plpy_exec.c:909
=======
#: plpy_exec.c:924
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] supprimé, ne peut pas modifier la ligne"

<<<<<<< HEAD
#: plpy_exec.c:914
=======
#: plpy_exec.c:929
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] n'est pas un dictionnaire"

<<<<<<< HEAD
#: plpy_exec.c:941
=======
#: plpy_exec.c:954
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "la clé TD[\"new\"] à la position ordinale %d n'est pas une chaîne"

<<<<<<< HEAD
#: plpy_exec.c:948
=======
#: plpy_exec.c:961
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering row"
msgstr ""
"la clé « %s » trouvée dans TD[\"new\"]  n'existe pas comme colonne\n"
"de la ligne impactée par le trigger"

<<<<<<< HEAD
#: plpy_exec.c:953
=======
#: plpy_exec.c:966
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "cannot set system attribute \"%s\""
msgstr "ne peut pas initialiser l'attribut système « %s »"

<<<<<<< HEAD
#: plpy_exec.c:1011
=======
#: plpy_exec.c:971
#, c-format
msgid "cannot set generated column \"%s\""
msgstr "ne peut pas initialiser la colonne générée « %s »"

#: plpy_exec.c:1029
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "while modifying trigger row"
msgstr "lors de la modification de la ligne du trigger"

<<<<<<< HEAD
#: plpy_exec.c:1072
=======
#: plpy_exec.c:1087
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "annulation forcée d'une sous-transaction qui n'a jamais été quittée"

#: plpy_main.c:109
#, c-format
msgid "multiple Python libraries are present in session"
msgstr "plusieurs bibliothèques Python sont présentes dans la session"

#: plpy_main.c:110
#, c-format
msgid "Only one Python major version can be used in one session."
msgstr "Seule une version majeure de Python peut être utilisée dans une session."

#: plpy_main.c:122
#, c-format
msgid "untrapped error in initialization"
msgstr "erreur non récupérée dans l'initialisation"

#: plpy_main.c:145
#, c-format
msgid "could not import \"__main__\" module"
msgstr "n'a pas pu importer le module « __main__ »"

<<<<<<< HEAD
#: plpy_main.c:174
=======
#: plpy_main.c:154
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not initialize globals"
msgstr "n'a pas pu initialiser les variables globales"

<<<<<<< HEAD
#: plpy_main.c:399
=======
#: plpy_main.c:352
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python procedure \"%s\""
msgstr "procédure PL/python « %s »"

<<<<<<< HEAD
#: plpy_main.c:402
=======
#: plpy_main.c:355
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python function \"%s\""
msgstr "fonction PL/python « %s »"

<<<<<<< HEAD
#: plpy_main.c:410
=======
#: plpy_main.c:363
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python anonymous code block"
msgstr "bloc de code PL/Python anonyme"

<<<<<<< HEAD
#: plpy_plpymodule.c:192 plpy_plpymodule.c:195
=======
#: plpy_plpymodule.c:168 plpy_plpymodule.c:171
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not import \"plpy\" module"
msgstr "n'a pas pu importer le module « plpy »"

<<<<<<< HEAD
#: plpy_plpymodule.c:210
=======
#: plpy_plpymodule.c:182
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not create the spiexceptions module"
msgstr "n'a pas pu créer le module « spiexceptions »"

<<<<<<< HEAD
#: plpy_plpymodule.c:218
=======
#: plpy_plpymodule.c:190
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not add the spiexceptions module"
msgstr "n'a pas pu ajouter le module « spiexceptions »"

<<<<<<< HEAD
#: plpy_plpymodule.c:286
=======
#: plpy_plpymodule.c:257
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not generate SPI exceptions"
msgstr "n'a pas pu générer les exceptions SPI"

<<<<<<< HEAD
#: plpy_plpymodule.c:454
=======
#: plpy_plpymodule.c:425
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not unpack arguments in plpy.elog"
msgstr "n'a pas pu déballer les arguments dans plpy.elog"

<<<<<<< HEAD
#: plpy_plpymodule.c:463
msgid "could not parse error message in plpy.elog"
msgstr "n'a pas pu analyser le message d'erreur dans plpy.elog"

#: plpy_plpymodule.c:480
=======
#: plpy_plpymodule.c:434
msgid "could not parse error message in plpy.elog"
msgstr "n'a pas pu analyser le message d'erreur dans plpy.elog"

#: plpy_plpymodule.c:451
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "argument 'message' given by name and position"
msgstr "argument 'message' donné par nom et position"

<<<<<<< HEAD
#: plpy_plpymodule.c:507
=======
#: plpy_plpymodule.c:478
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "'%s' is an invalid keyword argument for this function"
msgstr "'%s' est une argument mot-clé invalide pour cette fonction"

<<<<<<< HEAD
#: plpy_plpymodule.c:518 plpy_plpymodule.c:524
=======
#: plpy_plpymodule.c:489 plpy_plpymodule.c:495
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "invalid SQLSTATE code"
msgstr "code SQLSTATE invalide"

#: plpy_procedure.c:225
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "les fonctions trigger peuvent seulement être appelées par des triggers"

<<<<<<< HEAD
#: plpy_procedure.c:234
=======
#: plpy_procedure.c:229
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "les fonctions PL/python ne peuvent pas renvoyer le type %s"

<<<<<<< HEAD
#: plpy_procedure.c:312
=======
#: plpy_procedure.c:307
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "les fonctions PL/python ne peuvent pas accepter le type %s"

<<<<<<< HEAD
#: plpy_procedure.c:402
=======
#: plpy_procedure.c:395
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "n'a pas pu compiler la fonction PL/python « %s »"

<<<<<<< HEAD
#: plpy_procedure.c:405
=======
#: plpy_procedure.c:398
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "n'a pas pu compiler le bloc de code anonyme PL/python"

<<<<<<< HEAD
#: plpy_resultobject.c:150 plpy_resultobject.c:176 plpy_resultobject.c:202
=======
#: plpy_resultobject.c:117 plpy_resultobject.c:143 plpy_resultobject.c:169
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "command did not produce a result set"
msgstr "la commande n'a pas fourni d'ensemble de résultats"

<<<<<<< HEAD
#: plpy_spi.c:60
=======
#: plpy_spi.c:56
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "le second argument de plpy.prepare doit être une séquence"

<<<<<<< HEAD
#: plpy_spi.c:104
=======
#: plpy_spi.c:98
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare : le nom du type sur la position ordinale %d n'est pas une chaîne"

<<<<<<< HEAD
#: plpy_spi.c:176
=======
#: plpy_spi.c:170
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.prepare attendait une requête ou un plan"

<<<<<<< HEAD
#: plpy_spi.c:195
=======
#: plpy_spi.c:189
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute prends une séquence dans son second argument"

<<<<<<< HEAD
#: plpy_spi.c:305
=======
#: plpy_spi.c:297
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "échec de SPI_execute_plan : %s"

<<<<<<< HEAD
#: plpy_spi.c:347
=======
#: plpy_spi.c:339
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "SPI_execute failed: %s"
msgstr "échec de SPI_execute : %s"

#: plpy_subxactobject.c:92
#, c-format
msgid "this subtransaction has already been entered"
msgstr "cette sous-transaction est en cours d'utilisation"

#: plpy_subxactobject.c:98 plpy_subxactobject.c:156
#, c-format
msgid "this subtransaction has already been exited"
msgstr "déjà sorti de cette sous-transaction"

#: plpy_subxactobject.c:150
#, c-format
msgid "this subtransaction has not been entered"
msgstr "cette sous-transaction n'a jamais été utilisée"

#: plpy_subxactobject.c:162
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "il n'y a pas de transaction à quitter"

<<<<<<< HEAD
#: plpy_typeio.c:591
=======
#: plpy_typeio.c:588
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not import a module for Decimal constructor"
msgstr "n'a pas pu importer un module pour le constructeur Decimal"

<<<<<<< HEAD
#: plpy_typeio.c:595
=======
#: plpy_typeio.c:592
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "no Decimal attribute in module"
msgstr "pas d'attribut Decimal dans le module"

<<<<<<< HEAD
#: plpy_typeio.c:601
=======
#: plpy_typeio.c:598
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "conversion from numeric to Decimal failed"
msgstr "échec de la conversion numeric vers Decimal"

<<<<<<< HEAD
#: plpy_typeio.c:908
=======
#: plpy_typeio.c:912
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "n'a pas pu créer une représentation octets de l'objet Python"

<<<<<<< HEAD
#: plpy_typeio.c:1056
=======
#: plpy_typeio.c:1049
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not create string representation of Python object"
msgstr "n'a pas pu créer une représentation chaîne de caractères de l'objet Python"

<<<<<<< HEAD
#: plpy_typeio.c:1067
=======
#: plpy_typeio.c:1060
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not convert Python object into cstring: Python string representation appears to contain null bytes"
msgstr "n'a pas pu convertir l'objet Python en csting : la représentation de la chaîne Python contient des octets nuls"

<<<<<<< HEAD
#: plpy_typeio.c:1176
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "le nombre de dimensions du tableau dépasse le maximum autorisé (%d)"

#: plpy_typeio.c:1180
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "n'a pas pu déterminer la longueur de la séquence pour la valeur de retour de la fonction"

#: plpy_typeio.c:1183 plpy_typeio.c:1187
#, c-format
msgid "array size exceeds the maximum allowed"
msgstr "la taille du tableau dépasse le maximum permis"

#: plpy_typeio.c:1213
=======
#: plpy_typeio.c:1157
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "return value of function with array return type is not a Python sequence"
msgstr "la valeur de retour de la fonction de type tableau n'est pas une séquence Python"

<<<<<<< HEAD
#: plpy_typeio.c:1259
=======
#: plpy_typeio.c:1202
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not determine sequence length for function return value"
msgstr "n'a pas pu déterminer la longueur de la séquence pour la valeur de retour de la fonction"

<<<<<<< HEAD
#: plpy_typeio.c:1261
=======
#: plpy_typeio.c:1222 plpy_typeio.c:1237 plpy_typeio.c:1253
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "multidimensional arrays must have array expressions with matching dimensions"
msgstr ""
"les tableaux multidimensionnels doivent avoir des expressions de tableaux\n"
"avec les dimensions correspondantes"

<<<<<<< HEAD
#: plpy_typeio.c:1340
=======
#: plpy_typeio.c:1227
#, c-format
msgid "number of array dimensions exceeds the maximum allowed (%d)"
msgstr "le nombre de dimensions du tableau dépasse le maximum autorisé (%d)"

#: plpy_typeio.c:1329
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "malformed record literal: \"%s\""
msgstr "enregistrement litéral invalide : « %s »"

<<<<<<< HEAD
#: plpy_typeio.c:1341
#, c-format
msgid "Missing left parenthesis."
msgstr "Parenthèse gauche manquante"

#: plpy_typeio.c:1342 plpy_typeio.c:1543
=======
#: plpy_typeio.c:1330
#, c-format
msgid "Missing left parenthesis."
msgstr "Parenthèse gauche manquante."

#: plpy_typeio.c:1331 plpy_typeio.c:1532
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "To return a composite type in an array, return the composite type as a Python tuple, e.g., \"[('foo',)]\"."
msgstr "Pour renvoyer un type composite dans un tableau, renvoyez le type composite sous la forme d'un tuple Python, c'est-à-dire \"[('foo',)]\"."

<<<<<<< HEAD
#: plpy_typeio.c:1389
=======
#: plpy_typeio.c:1378
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "la clé « %s » introuvable dans la correspondance"

<<<<<<< HEAD
#: plpy_typeio.c:1390
=======
#: plpy_typeio.c:1379
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "To return null in a column, add the value None to the mapping with the key named after the column."
msgstr ""
"Pour renvoyer NULL dans une colonne, ajoutez la valeur None à la\n"
"correspondance de la clé nommée d'après la colonne."

<<<<<<< HEAD
#: plpy_typeio.c:1443
=======
#: plpy_typeio.c:1432
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr ""
"la longueur de la séquence renvoyée ne correspondait pas au nombre de\n"
"colonnes dans la ligne"

<<<<<<< HEAD
#: plpy_typeio.c:1541
=======
#: plpy_typeio.c:1530
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "l'attribut « %s » n'existe pas dans l'objet Python"

<<<<<<< HEAD
#: plpy_typeio.c:1544
=======
#: plpy_typeio.c:1533
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "To return null in a column, let the returned object have an attribute named after column with value None."
msgstr ""
"Pour renvoyer NULL dans une colonne, faites en sorte que l'objet renvoyé ait\n"
"un attribut nommé suivant la colonne de valeur None."

<<<<<<< HEAD
#: plpy_util.c:35
=======
#: plpy_util.c:31
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not convert Python Unicode object to bytes"
msgstr "n'a pas pu convertir l'objet Unicode Python en octets"

<<<<<<< HEAD
#: plpy_util.c:41
=======
#: plpy_util.c:37
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#, c-format
msgid "could not extract bytes from encoded string"
msgstr "n'a pas pu extraire les octets de la chaîne encodée"

<<<<<<< HEAD
#~ msgid "multidimensional arrays must have array expressions with matching dimensions. PL/Python function return value has sequence length %d while expected %d"
#~ msgstr ""
#~ "les tableaux multidimensionnels doivent avoir des expressions de tableaux\n"
#~ "avec des dimensions correspondantes. La valeur de retour de la fonction\n"
#~ "PL/Python a une longueur de séquence %d alors que %d est attendue"

#~ msgid "could not create the base SPI exceptions"
#~ msgstr "n'a pas pu créer les exceptions SPI de base"

#~ msgid "Python major version mismatch in session"
#~ msgstr "Différence de version majeure de Python dans la session"

#~ msgid "This session has previously used Python major version %d, and it is now attempting to use Python major version %d."
#~ msgstr ""
#~ "Cette session a auparavant utilisé la version majeure %d de Python et elle\n"
#~ "essaie maintenant d'utiliser la version majeure %d."

#~ msgid "Start a new session to use a different Python major version."
#~ msgstr ""
#~ "Lancez une nouvelle session pour utiliser une version majeure différente de\n"
#~ "Python."
=======
#~ msgid "PL/Python does not support conversion to arrays of row types."
#~ msgstr "PL/Python ne supporte pas les conversions vers des tableaux de types row."
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c

#~ msgid "PL/Python function \"%s\" could not execute plan"
#~ msgstr "la fonction PL/python « %s » n'a pas pu exécuter un plan"

<<<<<<< HEAD
#~ msgid "could not create string representation of Python object in PL/Python function \"%s\" while creating return value"
#~ msgstr ""
#~ "n'a pas pu créer la représentation en chaîne de caractère de l'objet\n"
#~ "Python dans la fonction PL/python « %s » lors de la création de la valeur\n"
#~ "de retour"

#~ msgid "could not compute string representation of Python object in PL/Python function \"%s\" while modifying trigger row"
=======
#~ msgid "PL/Python function \"%s\" failed"
#~ msgstr "échec de la fonction PL/python « %s »"

#~ msgid "PL/Python only supports one-dimensional arrays."
#~ msgstr "PL/Python supporte seulement les tableaux uni-dimensionnels."

#~ msgid "PL/Python: %s"
#~ msgstr "PL/python : %s"

#~ msgid "PyCObject_AsVoidPtr() failed"
#~ msgstr "échec de PyCObject_AsVoidPtr()"

#~ msgid "PyCObject_FromVoidPtr() failed"
#~ msgstr "échec de PyCObject_FromVoidPtr()"

#~ msgid "Python major version mismatch in session"
#~ msgstr "Différence de version majeure de Python dans la session"

#~ msgid "Start a new session to use a different Python major version."
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
#~ msgstr ""
#~ "n'a pas pu traiter la représentation de la chaîne d'un objet Python dans\n"
#~ "la fonction PL/Python « %s » lors de la modification de la ligne du trigger"

#~ msgid "PL/Python function \"%s\" failed"
#~ msgstr "échec de la fonction PL/python « %s »"

#~ msgid "out of memory"
#~ msgstr "mémoire épuisée"

#~ msgid "PL/Python: %s"
#~ msgstr "PL/python : %s"

#~ msgid "could not create procedure cache"
#~ msgstr "n'a pas pu créer le cache de procédure"

#~ msgid "unrecognized error in PLy_spi_execute_query"
#~ msgstr "erreur inconnue dans PLy_spi_execute_query"

#~ msgid "unrecognized error in PLy_spi_execute_plan"
#~ msgstr "erreur inconnue dans PLy_spi_execute_plan"

#~ msgid "unrecognized error in PLy_spi_prepare"
#~ msgstr "erreur inconnue dans PLy_spi_prepare"

#~ msgid "invalid arguments for plpy.prepare"
#~ msgstr "arguments invalides pour plpy.prepare"

#~ msgid "transaction aborted"
#~ msgstr "transaction annulée"

#~ msgid "PyCObject_FromVoidPtr() failed"
#~ msgstr "échec de PyCObject_FromVoidPtr()"

#~ msgid "PyCObject_AsVoidPtr() failed"
#~ msgstr "échec de PyCObject_AsVoidPtr()"

#~ msgid "unrecognized error in PLy_spi_execute_fetch_result"
#~ msgstr "erreur inconnue dans PLy_spi_execute_fetch_result"

#~ msgid "PL/Python does not support conversion to arrays of row types."
#~ msgstr "PL/Python ne supporte pas les conversions vers des tableaux de types row."

#~ msgid "plpy.prepare does not support composite types"
#~ msgstr "plpy.prepare ne supporte pas les types composites"

#~ msgid "the message is already specified"
#~ msgstr "le message est déjà spécifié"

#~ msgid "could not create new Python list"
#~ msgstr "n'a pas pu créer la nouvelle liste Python"

#~ msgid "PL/Python only supports one-dimensional arrays."
#~ msgstr "PL/Python supporte seulement les tableaux uni-dimensionnels."

#~ msgid "cannot convert multidimensional array to Python list"
#~ msgstr "ne peut pas convertir un tableau multidimensionnel en liste Python"

#~ msgid "plan.status takes no arguments"
#~ msgstr "plan.status ne prends pas d'arguments"

#~ msgid "could not create new dictionary"
#~ msgstr "n'a pas pu créer le nouveau dictionnaire"

#~ msgid "could not create exception \"%s\""
#~ msgstr "n'a pas pu créer l'exception « %s »"

#~ msgid "could not create globals"
#~ msgstr "n'a pas pu créer les globales"

#~ msgid "could not create new dictionary while building trigger arguments"
#~ msgstr ""
<<<<<<< HEAD
#~ "n'a pas pu créer un nouveau dictionnaire lors de la construction des\n"
#~ "arguments du trigger"
=======
#~ "Cette session a auparavant utilisé la version majeure %d de Python et elle\n"
#~ "essaie maintenant d'utiliser la version majeure %d."

#, c-format
#~ msgid "To construct a multidimensional array, the inner sequences must all have the same length."
#~ msgstr "Pour construire un tableau multidimensionnel, les séquences internes doivent toutes avoir la même longueur."

#, c-format
#~ msgid "array size exceeds the maximum allowed"
#~ msgstr "la taille du tableau dépasse le maximum permis"

#~ msgid "cannot convert multidimensional array to Python list"
#~ msgstr "ne peut pas convertir un tableau multidimensionnel en liste Python"

#~ msgid "could not compute string representation of Python object in PL/Python function \"%s\" while modifying trigger row"
#~ msgstr ""
#~ "n'a pas pu traiter la représentation de la chaîne d'un objet Python dans\n"
#~ "la fonction PL/Python « %s » lors de la modification de la ligne du trigger"

#~ msgid "could not create exception \"%s\""
#~ msgstr "n'a pas pu créer l'exception « %s »"

#~ msgid "could not create globals"
#~ msgstr "n'a pas pu créer les globales"

#~ msgid "could not create new Python list"
#~ msgstr "n'a pas pu créer la nouvelle liste Python"

#~ msgid "could not create new dictionary"
#~ msgstr "n'a pas pu créer le nouveau dictionnaire"

#~ msgid "could not create new dictionary while building trigger arguments"
#~ msgstr ""
#~ "n'a pas pu créer un nouveau dictionnaire lors de la construction des\n"
#~ "arguments du trigger"

#~ msgid "could not create procedure cache"
#~ msgstr "n'a pas pu créer le cache de procédure"

#~ msgid "could not create string representation of Python object in PL/Python function \"%s\" while creating return value"
#~ msgstr ""
#~ "n'a pas pu créer la représentation en chaîne de caractère de l'objet\n"
#~ "Python dans la fonction PL/python « %s » lors de la création de la valeur\n"
#~ "de retour"

#~ msgid "could not create the base SPI exceptions"
#~ msgstr "n'a pas pu créer les exceptions SPI de base"

#~ msgid "invalid arguments for plpy.prepare"
#~ msgstr "arguments invalides pour plpy.prepare"

#~ msgid "multidimensional arrays must have array expressions with matching dimensions. PL/Python function return value has sequence length %d while expected %d"
#~ msgstr ""
#~ "les tableaux multidimensionnels doivent avoir des expressions de tableaux\n"
#~ "avec des dimensions correspondantes. La valeur de retour de la fonction\n"
#~ "PL/Python a une longueur de séquence %d alors que %d est attendue"

#~ msgid "out of memory"
#~ msgstr "mémoire épuisée"

#~ msgid "plan.status takes no arguments"
#~ msgstr "plan.status ne prends pas d'arguments"

#~ msgid "plpy.prepare does not support composite types"
#~ msgstr "plpy.prepare ne supporte pas les types composites"

#~ msgid "the message is already specified"
#~ msgstr "le message est déjà spécifié"

#~ msgid "transaction aborted"
#~ msgstr "transaction annulée"

#~ msgid "unrecognized error in PLy_spi_execute_fetch_result"
#~ msgstr "erreur inconnue dans PLy_spi_execute_fetch_result"

#~ msgid "unrecognized error in PLy_spi_execute_plan"
#~ msgstr "erreur inconnue dans PLy_spi_execute_plan"

#~ msgid "unrecognized error in PLy_spi_execute_query"
#~ msgstr "erreur inconnue dans PLy_spi_execute_query"

#~ msgid "unrecognized error in PLy_spi_prepare"
#~ msgstr "erreur inconnue dans PLy_spi_prepare"

#, c-format
#~ msgid "wrong length of inner sequence: has length %d, but %d was expected"
#~ msgstr "mauvaise longueur de la séquence interne : a une longueur %d, mais %d était attendu"
>>>>>>> c1ff2d8bc5be55e302731a16aaff563b7f03ed7c
